### ISSUE TITLE
Error: driver not defined

### ISSUE THREAD

**Issue by moringaman** [bigchaindb/js-driver-orm#20]
Although bigchaindb-orm uses bgchaindb-driver  you cannot call **driver** unless you import the bigchaindb-driver library itself. This is not mentioned in the usage notes for js-driver-orm.

Is there any chance you could expose the the driver object so that bigchaindb-driver does not have to be imported separately?

**Comment by jernejpregelj** [comment]
@moringaman I'll check if I can expose driver safely

**Comment by moringaman** [comment]
Thanks

I also think it's worth pointing out that I get a 'only one instance of babel-polyfill permitted' error when I try to import bigchaindb-driver to use with the orm driver. (albeit using the vueJs framework, I haven't tried any other frameworks or even just vanilla javascript yet, but I thought you might want to know)

**Comment by jernejpregelj** [comment]
@moringaman The babel-polyfill problem is being solved shortly

**Comment by moringaman** [comment]
Ok Great, well I look forward to being able to use this library soon.

**Comment by DalderupMaurice** [comment]
driver is still not exposed. Could you have a look at this? 
It's not logic to pull the ORM to avoid the normal driver, but still having to pull in the complete driver to be able to generate keys

**Comment by moringaman** [comment]
Whats the latest on this, as it still does not seem to be usable by following the docs 4 months of waiting recent changes but still not working can anyone enlighten me???

**Comment by DalderupMaurice** [comment]
It works for me @moringaman 
have a look at my repo: https://github.com/DalderupMaurice/TU-BigchainDB-ORM-final
It's fully working with the newest update (BDB 2.0 with Tendermint)

**Comment by jernejpregelj** [comment]
Driver is now exposed in bdbOrm.driver

Example:
```javascript
const aliceKeypair = new bdbOrm.driver.Ed25519Keypair()
```
