### ISSUE TITLE
Bigchain db orm retrieval

### ISSUE THREAD

**Issue by SuganyaKrishnamoorthy** [bigchaindb/js-driver-orm#28]
All the operations in orm can be done through only asset id. Is there any option to retrieve data using string like in bigchain db driver?

**Comment by SaurabhVatsa** [comment]
Yes. All the assets are ultimately stored in BigchainDB in the usual form. So you can perform a `connection.searchMetaData(searchString)` and get the transaction. From the transaction, you can then get the `assetId` of the orm by calling, `tx.asset.data['-crabModel'].id` and now you have the asset as well as the orm object corresponding the asset.

**Comment by riyazpanarwala** [comment]
Can i also search using metadata ??

**Comment by jernejpregelj** [comment]
Searching is not possible at the moment is planned to be added in future releases.

Orm driver uses asset part of transaction for model and unique identifier storage. Everything else is stored in metadata.
