### ISSUE TITLE
Merge metadata rather than only displaying the latest

### ISSUE THREAD

**Issue by diminator** [bigchaindb/js-driver-orm#4]
When doing a partial update on the `metadata`, one would only see the diff right now.

example:
```
orm.model.create({key1: 'A', key2: 'B'})
    .then(object => object.append({key1: 'C'}))
    .then(updatedObject => console.log(object.metadata))
```
prints `{key1: 'C'}` rather than `{key1: 'C', key2: 'B'}`

**Comment by diminator** [comment]
or maybe have an additional "squash/merge" view

**Comment by jernejpregelj** [comment]
What about having metadata as merged metadata so `{key1: 'C', key2: 'B'}` and something like metadatahistory  that is `[{key1: 'C'},{key2: 'B'}]`. Also `metadata` is could be just `data` or some more descriptive name as you noted in [issue3](https://github.com/bigchaindb/js-driver-orm/issues/3)

**Comment by jernejpregelj** [comment]
#5
