### ISSUE TITLE
Retrieve doesn't works as intended

### ISSUE THREAD

**Issue by shekhar-shubhendu** [bigchaindb/js-driver-orm#64]
```javascript
import Orm from 'bigchaindb-orm';
const bdbOrm = new Orm("http://localhost:9984/api/v1/");
bdbOrm.define("myModel", "https://schema.org/v1/asset");
const aliceKeypair = new bdbOrm.driver.Ed25519Keypair();

// this works as intended and creates the asset.
bdbOrm.models.myModel
    .create({
        keypair: aliceKeypair,
        data: { key: 'dataValue' }
    })
    .then(asset => {
        console.log(asset.id)
    })

//this doesn't works as intended and returns an empty array
bdbOrm.models.myModel
    .retrieve()
    .then(assets => {
        console.log(assets.map(asset => asset.id))
}); 
```

## Actual Output
A blank array

## Expected Output
Array of assets found under its model

## Cause:
The retrieve performs the `searchAssets('-assetName')` and this only works if the asset name is part of the additional information passed inside like this(or in a object) `bdbOrm.define("myModel", "https://schema.org/v1/myModel");`.

**Comment by chpecson** [comment]
Same error occurs to me. Is there any way on how to resolve this issue.

**Comment by shekhar-shubhendu** [comment]
For now the best way to circumvent this is to use a JSON object as 2nd param which has the model name as a 'value' i.e. like
bdbOrm.define("myModel", {"name":"myModel", "schema": "https://schema.org/v1/asset"});

**Comment by jernejpregelj** [comment]
Fix in: https://github.com/bigchaindb/js-driver-orm/commit/9a30efde498cf40062ec79226e99a93deb3b1c7e
