### ISSUE TITLE
Possibility to specify a uuid() when importing an existing object from outside

### ISSUE THREAD

**Issue by KrishnaPG** [bigchaindb/js-driver-orm#74]
Currently asset create method always creates a new uuid (
https://github.com/bigchaindb/js-driver-orm/blob/364e9952849d690dbfd9083f02e16adf2ecac378/src/ormobject.js#L47 )

If we need to associate an existing uuid (say, imported from existing data records), api should allow it to be specified through inputs. It would be good if new `uuid()` is created only if one is not specified as part of the inputs.

**Comment by jernejpregelj** [comment]
Issue is implemented with #75
